
//AEHelgaShotsMetadataTemplate
global proc AEHelgaShotsMetadataTemplate( string $nodeName ) { 
    
    //Vars
    //-----------------------------------------
    //-----------------------------------------
    string $node[];
	tokenize $nodeName "." $node;


	



	//Header image
    //-----------------------------------------
    //-----------------------------------------
    
    //create header image
    editorTemplate -callCustom "helga_shots_metadata_create_header_image" "helga_shots_metadata_update_header_image" "Dummy";


	
	



	//scroll layout
    editorTemplate -beginScrollLayout;

    


    
    
    


    

    //Helga metadata attrs
    //-----------------------------------------
    //-----------------------------------------
    editorTemplate -beginLayout "Helga Shots Metadata" -collapse 0;

    //shot_name
    editorTemplate -annotation "For example:\n010_black_frame\n020_establisher\nShotnames are the same as the directories in here:\nY:/Production/3d/maya/scenes/shots" -addControl "shot_name";

    //alembic_path
    editorTemplate -annotation "Must be a full path. NOT relative to the maya project.\nGOOD: Y:/Production/3d/maya/cache/alembic/020_establisher \nBAD: cache/alembic/020_establisher" -addControl "alembic_path";

    //shot_cam
    editorTemplate -annotation "Unique path to the shot cam for the shot.\nYou can set it via the AssetManager" -addControl "shot_cam";

    //End Layout Input Color
    editorTemplate -endLayout;
    

   
    
    


    //Extra controls for unspecified attributes
    //-----------------------------------------
    //-----------------------------------------
    editorTemplate -addExtraControls; 
    
    //end scroll layout
    editorTemplate -endScrollLayout;






}









//Header image procedures
//-----------------------------------------
//-----------------------------------------

global proc helga_shots_metadata_create_header_image(string $nodeName)
{
    //Header
    image -w 400 -h 100 -image "helga_aetemplate_header_shot_metadata.png";
}


global proc helga_shots_metadata_update_header_image(string $nodeName)
{}










