
//AEHelgaAssetMetadataTemplate
global proc AEHelgaAssetMetadataTemplate( string $nodeName ) { 
    
    //Vars
    //-----------------------------------------
    //-----------------------------------------
    string $node[];
	tokenize $nodeName "." $node;


	



	//Header image
    //-----------------------------------------
    //-----------------------------------------
    
    //create header image
    editorTemplate -callCustom "helga_asset_metadata_create_header_image" "helga_asset_metadata_update_header_image" "Dummy";


	
	



	//scroll layout
    editorTemplate -beginScrollLayout;

    


    
    
    


    

    //Helga metadata attrs
    //-----------------------------------------
    //-----------------------------------------
    editorTemplate -beginLayout "Helga Asset Metadata" -collapse 0;

    //input_color
    editorTemplate -annotation "Propname:\nMust be unique and descriptive.\nYou can have several props of the same file referenced in, but they need a different propname in here.\nExample:\nstool_one_a\nstool_one_b\nstool_one_c\n...if you had 3 times the same stool referenced in." -addControl "asset_name";

    //End Layout Input Color
    editorTemplate -endLayout;
    

   
    
    


    //Extra controls for unspecified attributes
    //-----------------------------------------
    //-----------------------------------------
    editorTemplate -addExtraControls; 
    
    //end scroll layout
    editorTemplate -endScrollLayout;






}









//Header image procedures
//-----------------------------------------
//-----------------------------------------

global proc helga_asset_metadata_create_header_image(string $nodeName)
{
    //Header
    image -w 400 -h 100 -image "helga_aetemplate_header.png";
}


global proc helga_asset_metadata_update_header_image(string $nodeName)
{}










